# Generated by Django 3.1.7 on 2021-04-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=0, max_length=256),
        ),
    ]
